"use client";

import { useState, useEffect, useRef } from "react";
import { InAppSheet } from "./in-app-sheet";

/** Kit version — injected at build time via tsup define */
declare const __KIT_VERSION__: string;
const KIT_VERSION = typeof __KIT_VERSION__ !== "undefined" ? __KIT_VERSION__ : "dev";

/**
 * Site slug for the m1k.app visitor tracker. Read from `NEXT_PUBLIC_M1K_SLUG`
 * (inlined by Next at build) when no explicit `slug` prop is given. Wrapped in
 * try/catch so it's a no-op under bundlers where `process` is undefined (Vite…).
 */
function resolveEnvSlug(): string | undefined {
  try {
    return process.env.NEXT_PUBLIC_M1K_SLUG || undefined;
  } catch {
    return undefined;
  }
}

interface UsageInfo {
  used: number;
  total: number;
  percent: number;
}

interface KitStats {
  generatedAt: string;
  kitVersion: string;
  source: {
    dir: string;
    files: number;
    totalLines: number;
    codeLines: number;
  };
  kit: {
    features: { name: string; loc: number; category: string }[];
    savedLines: number;
    savedKB: number;
    savedA4: number;
    savedPercent: number;
    usage: {
      component: UsageInfo;
      hook: UsageInfo;
      util: UsageInfo;
    };
  };
}

export interface PoweredByKitProps {
  /** Path to kit-stats.json. Default: "/kit-stats.json" */
  statsUrl?: string;
  /** Override version string */
  version?: string;
  /** "default" for inside AppShell, "overlay" for on top of Watermark background */
  variant?: "default" | "overlay";
  /**
   * m1k.app visitor-tracker slug. When set (explicitly or via the
   * `NEXT_PUBLIC_M1K_SLUG` env var) a tiny hidden beacon counts each page view.
   * No slug → no tracking (off by default). Register one with `npx m1kkit track`.
   */
  slug?: string;
  /** Tracker host. Default: "m1k.app" */
  trackerHost?: string;
  /** Set false to disable the visitor beacon even when a slug is present */
  track?: boolean;
  /**
   * Whether the registered site has been claimed (귀속/인증) to an m1k.app account.
   * When tracking is active but this is false, the badge shows a "미인증" marker.
   * Set true after running `npx m1kkit claim`. Defaults to false.
   */
  claimed?: boolean;
  /**
   * Visitor counts to display ({ today, total }). If omitted, fetched from
   * `https://<trackerHost>/api/sites/<slug>` (needs CORS). Pass explicitly to
   * avoid the fetch (SSR, custom source, or cross-origin without CORS).
   */
  counts?: { today?: number; total?: number };
  className?: string;
}

/**
 * "Powered by @m1kapp/kit" badge + credits sheet.
 * Place outside AppShell, in the Watermark padding area.
 *
 * Fetches /kit-stats.json (generated by `m1kkit stats`) on first open
 * to show real code analysis results.
 */
export function PoweredByKit({ statsUrl = "/kit-stats.json", version, variant = "default", slug, trackerHost = "m1k.app", track = true, claimed = false, counts, className = "" }: PoweredByKitProps) {
  const [open, setOpen] = useState(false);
  const trackerSlug = slug ?? resolveEnvSlug();
  const tracking = !!(track && trackerSlug);
  const unverified = tracking && !claimed;
  const [stats, setStats] = useState<KitStats | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  // Footer carousel — one-way loop: [counter, powered, counter-clone].
  const [idx, setIdx] = useState(0);
  const [anim, setAnim] = useState(true);
  const touchX = useRef(0);
  const moved = useRef(false);

  // Visitor counts — explicit prop wins, else fetched from m1k.app's lean public
  // count endpoint (?view=count → { today, total } only, CORS-enabled).
  const [fetched, setFetched] = useState<{ today: number; total: number } | null>(null);
  const visitorCounts = counts
    ? { today: counts.today ?? 0, total: counts.total ?? 0 }
    : fetched;

  useEffect(() => {
    if (!tracking || counts) return;
    let alive = true;
    fetch(`https://${trackerHost}/api/sites/${encodeURIComponent(trackerSlug!)}?view=count`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (alive && d) setFetched({ today: Number(d.todayCount ?? d.today ?? 0), total: Number(d.total ?? 0) }); })
      .catch(() => { /* CORS/offline — counter just won't show */ });
    return () => { alive = false; };
  }, [tracking, counts, trackerHost, trackerSlug]);

  const hasCounter = tracking && !!visitorCounts;

  // one-way auto-advance every 10s (pause while the sheet is open)
  useEffect(() => {
    if (!hasCounter || open) return;
    const id = setInterval(() => setIdx((i) => Math.min(i + 1, 2)), 10_000);
    return () => clearInterval(id);
  }, [hasCounter, open]);

  // seamless loop: after sliding onto the clone (idx 2), snap back to 0 without animation
  useEffect(() => {
    if (idx === 2) {
      const t = setTimeout(() => { setAnim(false); setIdx(0); }, 540);
      return () => clearTimeout(t);
    }
    if (!anim) {
      const t = setTimeout(() => setAnim(true), 40);
      return () => clearTimeout(t);
    }
  }, [idx, anim]);

  const ver = version || KIT_VERSION;

  useEffect(() => {
    if (!open || stats || loading) return;
    setLoading(true);
    fetch(statsUrl)
      .then((r) => {
        if (!r.ok) throw new Error("not found");
        return r.json();
      })
      .then((data) => setStats(data))
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, [open, stats, loading, statsUrl]);

  const components = stats?.kit.features.filter((f) => f.category === "component") || [];
  const hooks = stats?.kit.features.filter((f) => f.category === "hook") || [];
  const utils = stats?.kit.features.filter((f) => f.category === "util") || [];

  const barClass = `w-full text-[11px] text-center select-none transition-colors ${
    variant === "overlay"
      ? "max-sm:py-1 max-sm:text-zinc-400 max-sm:dark:text-zinc-500 max-sm:bg-white/95 max-sm:dark:bg-zinc-950/95 max-sm:backdrop-blur-sm max-sm:border-t max-sm:border-zinc-100 max-sm:dark:border-zinc-800 sm:py-0.5 sm:text-white/50"
      : "py-1.5 text-zinc-400 dark:text-zinc-500"
  } ${className}`;
  const barStyle = variant === "overlay" ? { paddingBottom: `max(0.25rem, env(safe-area-inset-bottom))` } : undefined;
  const badgeUrl = trackerSlug ? `https://${trackerHost}/badge/${encodeURIComponent(trackerSlug)}.svg` : "";
  const openOnTap = () => { if (!moved.current) setOpen(true); };

  return (
    <>
      {tracking ? (
        // Footer — one-way looping carousel between the visitor counter and the
        // powered-by credit. A hidden badge img does the actual counting (once).
        (() => {
          const counterFace = (
            <button
              type="button"
              onClick={openOnTap}
              aria-label="방문자 통계"
              className="flex w-full shrink-0 basis-full items-center justify-center cursor-pointer"
            >
              {visitorCounts && (
                <span>
                  TODAY <b className="font-bold">{visitorCounts.today.toLocaleString()}</b>
                  {"  ·  "}
                  TOTAL <b className="font-bold">{visitorCounts.total.toLocaleString()}</b>
                </span>
              )}
            </button>
          );
          const poweredFace = (
            <button
              type="button"
              onClick={openOnTap}
              className="flex w-full shrink-0 basis-full items-center justify-center gap-1 cursor-pointer"
            >
              {unverified && <span className="text-amber-500" title="방문자 추적 연결됨 · 아직 미인증">●</span>}
              <span>v{ver} · powered by @m1kapp/kit{unverified && " · 미인증"}</span>
            </button>
          );
          return (
            <div
              className={barClass}
              style={barStyle}
              onTouchStart={(e) => {
                const x = e.touches[0]?.clientX;
                if (x !== undefined) { touchX.current = x; moved.current = false; }
              }}
              onTouchMove={(e) => {
                const x = e.touches[0]?.clientX;
                if (x !== undefined && Math.abs(x - touchX.current) > 10) moved.current = true;
              }}
              onTouchEnd={(e) => {
                const x = e.changedTouches[0]?.clientX;
                if (x === undefined) return;
                // one-way; clamp at the clone (idx 2) so a swipe during the
                // 540ms snap-back window can't overshoot into a blank frame
                if (Math.abs(touchX.current - x) > 40) setIdx((i) => Math.min(i + 1, 2));
              }}
            >
              {/* hidden beacon — counts each page view once */}
              <img src={badgeUrl} alt="" aria-hidden="true" width={1} height={1} decoding="async" style={{ position: "absolute", width: 1, height: 1, opacity: 0, pointerEvents: "none" }} />
              {hasCounter ? (
                <div className="overflow-hidden">
                  <div
                    className={`flex ${anim ? "transition-transform duration-500 ease-out" : ""}`}
                    style={{ transform: `translateX(-${idx * 100}%)` }}
                  >
                    {counterFace}
                    {poweredFace}
                    {counterFace}
                  </div>
                </div>
              ) : (
                poweredFace
              )}
            </div>
          );
        })()
      ) : (
        <button onClick={() => setOpen(true)} className={`${barClass} cursor-pointer`} style={barStyle}>
          v{ver} · powered by @m1kapp/kit
        </button>
      )}

      <InAppSheet open={open} onClose={() => setOpen(false)} title="@m1kapp/kit" fullHeight>
        <div className="px-5 pb-8 space-y-6 overflow-y-auto flex-1">
          {/* Version */}
          <div className="flex items-center gap-2">
            <span className="text-sm font-mono px-2.5 py-1 rounded bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400">
              v{ver}
            </span>
            <span className="text-sm text-zinc-400 dark:text-zinc-500">
              사이드 프로젝트를 위한 UI · SEO · PWA 킷
            </span>
          </div>

          {/* Visitor-tracker status */}
          {tracking && (
            <div className={`rounded-xl border p-4 ${
              claimed
                ? "bg-emerald-50 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-800"
                : "bg-amber-50 dark:bg-amber-950/30 border-amber-200 dark:border-amber-800"
            }`}>
              <div className="flex items-center gap-2">
                <span className={`inline-block h-2 w-2 rounded-full ${claimed ? "bg-emerald-500" : "bg-amber-500"}`} />
                <p className={`text-sm font-semibold ${claimed ? "text-emerald-700 dark:text-emerald-400" : "text-amber-700 dark:text-amber-400"}`}>
                  방문자 추적 연결됨 · {claimed ? "인증됨" : "아직 미인증"}
                </p>
              </div>
              {!claimed && (
                <div className="mt-2 space-y-1.5">
                  <p className="text-xs text-zinc-500 dark:text-zinc-400">
                    이 사이트는 추적이 붙었지만 아직 내 계정에 귀속(인증)되지 않았어요.
                  </p>
                  <code className="block rounded-lg bg-zinc-900 dark:bg-zinc-950 px-3 py-2 text-xs text-emerald-400 font-mono">npx m1kkit claim</code>
                </div>
              )}
            </div>
          )}

          {loading && (
            <div className="text-sm text-zinc-400 dark:text-zinc-500 py-8 text-center">
              코드 분석 결과를 불러오는 중...
            </div>
          )}

          {error && (
            <div className="rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-5 space-y-4">
              <div>
                <p className="text-sm font-semibold text-zinc-700 dark:text-zinc-300">
                  코드 분석 데이터가 아직 없어요
                </p>
                <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-1">
                  아래 명령어를 한 번 실행하면 이 화면에 프로젝트 분석 결과가 표시됩니다.
                </p>
              </div>

              <div className="rounded-lg bg-zinc-900 dark:bg-zinc-950 p-3">
                <code className="text-xs text-emerald-400 font-mono">npx m1kkit stats</code>
              </div>

              <div className="space-y-2">
                <p className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
                  매번 자동으로 하려면 package.json에 추가:
                </p>
                <div className="rounded-lg bg-zinc-900 dark:bg-zinc-950 p-3 space-y-1">
                  <p className="text-[11px] text-zinc-400 font-mono">
                    {'"dev": "m1kkit stats && next dev"'}
                  </p>
                  <p className="text-[11px] text-zinc-400 font-mono">
                    {'"build": "m1kkit stats && next build"'}
                  </p>
                </div>
                <p className="text-[11px] text-zinc-400 dark:text-zinc-500">
                  next 대신 vite, remix 등 본인 프레임워크로 바꾸세요.
                </p>
              </div>
            </div>
          )}

          {stats && (() => {
            const totalIfNoKit = stats.source.codeLines + stats.kit.savedLines;
            return (
            <>
              {/* kit 없이 만들었다면 */}
              <div className="rounded-xl bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-4">
                <p className="text-xs text-zinc-400 dark:text-zinc-500 mb-1">kit 없이 직접 만들었다면</p>
                <p className="text-lg font-bold text-zinc-800 dark:text-zinc-200">
                  {totalIfNoKit.toLocaleString()}줄이 필요했을 거예요
                </p>
                <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-0.5">
                  {stats.source.files}개 파일 · {stats.source.dir}/
                </p>
              </div>

              {/* Code savings */}
              <div className="rounded-xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 p-5">
                <p className="text-sm text-emerald-600 dark:text-emerald-500">
                  그 중 <span className="text-3xl font-bold text-emerald-700 dark:text-emerald-400">{stats.kit.savedPercent}%</span>를 kit이 대신 처리
                </p>
                <div className="mt-3 space-y-1.5">
                  <div className="flex justify-between text-xs">
                    <span className="text-zinc-500 dark:text-zinc-400">내가 쓴 코드</span>
                    <span className="font-mono text-zinc-700 dark:text-zinc-300">{stats.source.codeLines.toLocaleString()}줄</span>
                  </div>
                  <div className="flex justify-between text-xs">
                    <span className="text-emerald-600 dark:text-emerald-400">kit이 해준 코드</span>
                    <span className="font-mono text-emerald-700 dark:text-emerald-300">{stats.kit.savedLines.toLocaleString()}줄</span>
                  </div>
                </div>
                <div className="mt-3 flex items-baseline gap-3 text-xs text-emerald-500 dark:text-emerald-600">
                  <span>{stats.kit.savedKB}KB</span>
                  <span>·</span>
                  <span>A4 {stats.kit.savedA4}장 분량 절약</span>
                </div>
              </div>

              {/* Used components */}
              {components.length > 0 && (
                <div>
                  <div className="flex items-baseline justify-between mb-3">
                    <p className="text-sm font-semibold text-zinc-600 dark:text-zinc-300">
                      컴포넌트
                    </p>
                    <p className="text-xs text-zinc-400 dark:text-zinc-500">
                      {stats.kit.usage.component.used}/{stats.kit.usage.component.total}개 사용 ({stats.kit.usage.component.percent}%)
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {components.map((f) => (
                      <span
                        key={f.name}
                        className="text-sm font-mono px-3 py-1 rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300"
                      >
                        {f.name}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Used hooks */}
              {hooks.length > 0 && (
                <div>
                  <div className="flex items-baseline justify-between mb-3">
                    <p className="text-sm font-semibold text-zinc-600 dark:text-zinc-300">
                      훅
                    </p>
                    <p className="text-xs text-zinc-400 dark:text-zinc-500">
                      {stats.kit.usage.hook.used}/{stats.kit.usage.hook.total}개 사용 ({stats.kit.usage.hook.percent}%)
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {hooks.map((f) => (
                      <span
                        key={f.name}
                        className="text-sm font-mono px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-950/30 text-blue-700 dark:text-blue-400 border border-blue-200 dark:border-blue-800"
                      >
                        {f.name}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Used utils */}
              {utils.length > 0 && (
                <div>
                  <div className="flex items-baseline justify-between mb-3">
                    <p className="text-sm font-semibold text-zinc-600 dark:text-zinc-300">
                      유틸리티
                    </p>
                    <p className="text-xs text-zinc-400 dark:text-zinc-500">
                      {stats.kit.usage.util.used}/{stats.kit.usage.util.total}개 사용 ({stats.kit.usage.util.percent}%)
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {utils.map((f) => (
                      <span
                        key={f.name}
                        className="text-sm font-mono px-3 py-1 rounded-full bg-purple-50 dark:bg-purple-950/30 text-purple-700 dark:text-purple-400 border border-purple-200 dark:border-purple-800"
                      >
                        {f.name}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* 분석 시점 + 갱신 안내 (데이터가 있을 땐 '실행'이 아니라 '갱신') */}
              <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-zinc-300 dark:text-zinc-600">
                <span>분석: {new Date(stats.generatedAt).toLocaleDateString("ko-KR")}</span>
                <span aria-hidden>·</span>
                <span>갱신하려면</span>
                <code className="rounded bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 font-mono text-zinc-500 dark:text-zinc-400">npx m1kkit stats</code>
              </div>
            </>
            );
          })()}

          {/* Footer */}
          <div className="pt-4 border-t border-zinc-100 dark:border-zinc-800">
            <a
              href="https://github.com/m1kapp/kit"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 transition-colors"
            >
              github.com/m1kapp/kit →
            </a>
          </div>
        </div>
      </InAppSheet>
    </>
  );
}
