"use client";

import { useState, useEffect, useRef } from "react";
import { ChevronLeftIcon, ChevronRightIcon } from "./_icons";
import { VisitorStatsSheet } from "./visitor-stats-sheet";
import { CreditsSheet } from "./credits-sheet";

/** Kit version — injected at build time via tsup define */
declare const __KIT_VERSION__: string;
const KIT_VERSION = typeof __KIT_VERSION__ !== "undefined" ? __KIT_VERSION__ : "dev";

/**
 * Site slug for the m1k.app visitor tracker. Read from `NEXT_PUBLIC_M1K_SLUG`
 * (inlined by Next at build) when no explicit `slug` prop is given. Wrapped in
 * try/catch so it's a no-op under bundlers where `process` is undefined (Vite…).
 */
function resolveEnvSlug(): string | undefined {
  try {
    return process.env.NEXT_PUBLIC_M1K_SLUG || undefined;
  } catch {
    return undefined;
  }
}

export interface PoweredByKitProps {
  /** Path to kit-stats.json. Default: "/kit-stats.json" */
  statsUrl?: string;
  /** Override version string */
  version?: string;
  /** "default" for inside AppShell, "overlay" for on top of Watermark background */
  variant?: "default" | "overlay";
  /**
   * m1k.app visitor-tracker slug. When set (explicitly or via the
   * `NEXT_PUBLIC_M1K_SLUG` env var) a tiny hidden beacon counts each page view.
   * No slug → no tracking (off by default). Register one with `npx m1kkit track`.
   */
  slug?: string;
  /** Tracker host. Default: "www.m1k.app" (apex m1k.app는 www로 307 리다이렉트 → cross-origin fetch가 CORS로 깨지므로 www 직결) */
  trackerHost?: string;
  /** Set false to disable the visitor beacon even when a slug is present */
  track?: boolean;
  /**
   * Whether the registered site has been claimed (귀속/인증) to an m1k.app account.
   * When tracking is active but this is false, the badge shows a "미인증" marker.
   * Set true after running `npx m1kkit claim`. Defaults to false.
   */
  claimed?: boolean;
  /**
   * Visitor counts to display ({ today, total }). If omitted, fetched from
   * `https://<trackerHost>/api/sites/<slug>` (needs CORS). Pass explicitly to
   * avoid the fetch (SSR, custom source, or cross-origin without CORS).
   */
  counts?: { today?: number; total?: number };
  className?: string;
}

/** 방문자 카운트 — 명시 prop 우선, 없으면 count 전용 공개 API에서 fetch */
function useVisitorCounts(
  tracking: boolean,
  counts: PoweredByKitProps["counts"],
  trackerHost: string,
  trackerSlug: string | undefined,
) {
  const [fetched, setFetched] = useState<{ today: number; total: number } | null>(null);

  useEffect(() => {
    if (!tracking || counts) return;
    let alive = true;
    fetch(`https://${trackerHost}/api/sites/${encodeURIComponent(trackerSlug!)}?view=count`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (alive && d) setFetched({ today: Number(d.todayCount ?? d.today ?? 0), total: Number(d.total ?? 0) }); })
      .catch(() => { /* CORS/offline — counter just won't show */ });
    return () => { alive = false; };
  }, [tracking, counts, trackerHost, trackerSlug]);

  if (counts) return { today: counts.today ?? 0, total: counts.total ?? 0 };
  return fetched;
}

/**
 * "Powered by @m1kapp/kit" badge + credits sheet.
 * Place outside AppShell, in the Watermark padding area.
 *
 * Fetches /kit-stats.json (generated by `m1kkit stats`) on first open
 * to show real code analysis results.
 */
export function PoweredByKit({ statsUrl = "/kit-stats.json", version, variant = "default", slug, trackerHost = "www.m1k.app", track = true, claimed = false, counts, className = "" }: PoweredByKitProps) {
  const [open, setOpen] = useState(false);
  const [statsOpen, setStatsOpen] = useState(false);
  const trackerSlug = slug ?? resolveEnvSlug();
  const tracking = !!(track && trackerSlug);
  const unverified = tracking && !claimed;

  // Footer carousel between two faces: [counter, powered]. Arrows + swipe + auto.
  const [idx, setIdx] = useState(0);
  const touchX = useRef(0);
  const moved = useRef(false);
  const go = (dir: number) => setIdx((i) => (i + dir + 2) % 2);

  const visitorCounts = useVisitorCounts(tracking, counts, trackerHost, trackerSlug);
  const hasCounter = tracking && !!visitorCounts;

  // auto-advance every 10s (pause while a sheet is open)
  useEffect(() => {
    if (!hasCounter || open || statsOpen) return;
    const id = setInterval(() => setIdx((i) => (i + 1) % 2), 10_000);
    return () => clearInterval(id);
  }, [hasCounter, open, statsOpen]);

  const ver = version || KIT_VERSION;

  const barClass = `w-full text-[11px] text-center select-none transition-colors ${
    variant === "overlay"
      ? "max-sm:py-1 max-sm:text-zinc-400 max-sm:dark:text-zinc-500 max-sm:bg-white/95 max-sm:dark:bg-zinc-950/95 max-sm:backdrop-blur-sm max-sm:border-t max-sm:border-zinc-100 max-sm:dark:border-zinc-800 sm:py-0.5 sm:text-white/50"
      : "py-1.5 text-zinc-400 dark:text-zinc-500"
  } ${className}`;
  const barStyle = variant === "overlay" ? { paddingBottom: `max(0.25rem, env(safe-area-inset-bottom))` } : undefined;
  const badgeUrl = trackerSlug ? `https://${trackerHost}/badge/${encodeURIComponent(trackerSlug)}.svg` : "";
  const openOnTap = () => { if (!moved.current) setOpen(true); };
  const openStatsOnTap = () => { if (!moved.current) setStatsOpen(true); };
  const sitePageUrl = trackerSlug ? `https://${trackerHost}/${encodeURIComponent(trackerSlug)}` : "";

  const counterFace = (
    <button
      type="button"
      onClick={openStatsOnTap}
      aria-label="방문자 통계"
      className="flex w-full shrink-0 basis-full items-center justify-center cursor-pointer"
    >
      {visitorCounts && (
        <span>
          TODAY <b className="font-bold">{visitorCounts.today.toLocaleString()}</b>
          {"  ·  "}
          TOTAL <b className="font-bold">{visitorCounts.total.toLocaleString()}</b>
        </span>
      )}
    </button>
  );
  const poweredFace = (
    <button
      type="button"
      onClick={openOnTap}
      className="flex w-full shrink-0 basis-full items-center justify-center gap-1 cursor-pointer"
    >
      {unverified && <span className="text-amber-500" title="방문자 추적 연결됨 · 아직 미인증">●</span>}
      <span>v{ver} · powered by @m1kapp/kit{unverified && " · 미인증"}</span>
    </button>
  );

  return (
    <>
      {tracking ? (
        // Footer — carousel between the visitor counter and the powered-by
        // credit, navigable by arrows/swipe. A hidden badge img counts once.
        <div
          className={barClass}
          style={barStyle}
          onTouchStart={(e) => {
            const x = e.touches[0]?.clientX;
            if (x !== undefined) { touchX.current = x; moved.current = false; }
          }}
          onTouchMove={(e) => {
            const x = e.touches[0]?.clientX;
            if (x !== undefined && Math.abs(x - touchX.current) > 10) moved.current = true;
          }}
          onTouchEnd={(e) => {
            const x = e.changedTouches[0]?.clientX;
            if (x === undefined) return;
            const dx = touchX.current - x;       // +: swiped left → next
            if (Math.abs(dx) > 40) go(dx > 0 ? 1 : -1);
          }}
        >
          {/* hidden beacon — counts each page view once */}
          <img src={badgeUrl} alt="" aria-hidden="true" width={1} height={1} decoding="async" style={{ position: "absolute", width: 1, height: 1, opacity: 0, pointerEvents: "none" }} />
          {hasCounter ? (
            <div className="relative">
              <div className="overflow-hidden mx-5">
                <div
                  className="flex transition-transform duration-500 ease-out"
                  style={{ transform: `translateX(-${idx * 100}%)` }}
                >
                  {counterFace}
                  {poweredFace}
                </div>
              </div>
              <button
                type="button"
                onClick={() => go(-1)}
                aria-label="이전"
                className="absolute inset-y-0 left-0 flex items-center px-1 opacity-50 hover:opacity-100 transition-opacity cursor-pointer"
              >
                <ChevronLeftIcon size={14} />
              </button>
              <button
                type="button"
                onClick={() => go(1)}
                aria-label="다음"
                className="absolute inset-y-0 right-0 flex items-center px-1 opacity-50 hover:opacity-100 transition-opacity cursor-pointer"
              >
                <ChevronRightIcon size={14} />
              </button>
            </div>
          ) : (
            poweredFace
          )}
        </div>
      ) : (
        <button onClick={() => setOpen(true)} className={`${barClass} cursor-pointer`} style={barStyle}>
          v{ver} · powered by @m1kapp/kit
        </button>
      )}

      {/* 방문자 통계 상세 시트 — 카운터 클릭 */}
      <VisitorStatsSheet
        open={statsOpen}
        onClose={() => setStatsOpen(false)}
        trackerHost={trackerHost}
        trackerSlug={trackerSlug}
        sitePageUrl={sitePageUrl}
      />

      {/* 크레딧 시트 — powered-by 클릭 */}
      <CreditsSheet
        open={open}
        onClose={() => setOpen(false)}
        ver={ver}
        tracking={tracking}
        claimed={claimed}
        statsUrl={statsUrl}
      />
    </>
  );
}
