import { readFileSync, writeFileSync, mkdirSync } from "fs";

const css = readFileSync(".tmp/styles.css", "utf8");

// Embed into TS for JS-injection fallback
const content = `// AUTO-GENERATED by build — do not edit\nexport const COMPILED_CSS = ${JSON.stringify(css)};\n`;
writeFileSync("src/ui/_compiled-styles.ts", content);

// Also ship as a static CSS file for SSR-safe import
mkdirSync("dist", { recursive: true });
writeFileSync("dist/styles.css", css);

console.log(`✓ Embedded ${css.length} bytes of CSS`);
